name: adventurenotes
version: 1.0
main: jesse.adventurenotes.App
api-version: 1.19
authors: [ Jesse ]
description: A simple plugin for taking notes while playing minecraft maps
commands:
   note:
      description: Adds a note to the global journal
      usage: /note <msg>
      permission: adventurenotes.commands.addnote
   addnote:
      description: Adds a note to the global journal
      usage: /note <msg>
      permission: adventurenotes.commands.addnote
   read:
      description: Reads a note from the global journal
      usage: /read <index>
      permission: adventurenotes.commands.read
   edit:
      description: Edits a note from the global journal
      usage: /edit <index>
      permission: adventurenotes.commands.edit
   delete:
      description: Deletes a note from the global journal
      usage: /delete <index>
      permission: adventurenotes.commands.delete
   acl:
      description: Toggles active chat listener
      usage: /acl
      permission: adventurenotes.commands.acl
   chatmenu:
      description: Prints to chat
      usage: /chatmenu
      permission: adventurenotes.commands.chatmenu